In [7]:
import pandas as pd
df1 = pd.read_csv("students.csv")
df1

,StudentID,Name,Age,Gender,City,Course,Marks,Attendance,Passed
0,101,Alice,20,Female,Delhi,Python,85,92,Yes
1,102,Bob,21,Male,Mumbai,Java,78,88,Yes
2,103,Charlie,22,Male,Bangalore,Python,92,95,Yes
3,104,Diana,20,Female,Pune,C++,67,80,Yes
4,105,Ethan,23,Male,Hyderabad,Java,55,72,No
5,106,Fiona,21,Female,Chennai,Python,89,96,Yes
6,107,George,22,Male,Delhi,C++,48,68,No
7,108,Hannah,20,Female,Mumbai,Java,74,85,Yes
8,109,Ian,23,Male,Pune,Python,61,78,Yes
9,110,Julia,21,Female,Bangalore,C++,95,98,Yes

In [8]:
df.head() # first 5 rows
df.head(10) # first 10 rows
df.tail() # last 5 rows

   StudentID    Name  Age  Gender       City  Course  Marks  Attendance Passed
5        106   Fiona   21  Female    Chennai  Python     89          96    Yes
6        107  George   22    Male      Delhi     C++     48          68     No
7        108  Hannah   20  Female     Mumbai    Java     74          85    Yes
8        109     Ian   23    Male       Pune  Python     61          78    Yes
9        110   Julia   21  Female  Bangalore     C++     95          98    Yes

In [9]:
df.info() # information about columns
df.describe() # statistics of columns
df.columns # column names
df.shape # size of file

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Gender      10 non-null     object
 4   City        10 non-null     object
 5   Course      10 non-null     object
 6   Marks       10 non-null     int64
 7   Attendance  10 non-null     int64
 8   Passed      10 non-null     object
dtypes: int64(4), object(5)
memory usage: 852.0+ bytes

(10, 9)

# Data Selection & Filtering

In [10]:
# Selecting Rows & Columns

df["Name"] # single column (series)
df[["Name","Age"]] # data frame

      Name  Age
0    Alice   20
1      Bob   21
2  Charlie   22
3    Diana   20
4    Ethan   23
5    Fiona   21
6   George   22
7   Hannah   20
8      Ian   23
9    Julia   21

In [11]:
# Selecting Rows by Index

df.loc[2] # First row (by label)
df.iloc[2] # First row (by position)

print(df.loc[0, "Name"])  # Value at row 0, column 'Name'
print(df.iloc[0, 1])  # Value at row 0, column at index 1

print(df.loc[0:2, ["Name", "Age"]]) # Rows 0 to 2, selected columns
print()
print(df.iloc[0:2, 0:2] )# Rows and cols by index position

# faster way - similar to loc just no slicing

df.at[0, "Name"] # Fast label-based access
df.iat[0, 1]  # Fast position based access

Alice
Alice
      Name  Age
0    Alice   20
1      Bob   21
2  Charlie   22

   StudentID   Name
0        101  Alice
1        102    Bob

'Alice'

# Filtering with Conditions

In [16]:
df[df["Age"]>20]

,StudentID,Name,Age,Gender,City,Course,Marks,Attendance,Passed
1,102,Bob,21,Male,Mumbai,Java,78,88,Yes
2,103,Charlie,22,Male,Bangalore,Python,92,95,Yes
4,105,Ethan,23,Male,Hyderabad,Java,55,72,No
5,106,Fiona,21,Female,Chennai,Python,89,96,Yes
6,107,George,22,Male,Delhi,C++,48,68,No
8,109,Ian,23,Male,Pune,Python,61,78,Yes
9,110,Julia,21,Female,Bangalore,C++,95,98,Yes

In [20]:
# syntax - df[(df[condn])&(df[condn])]

df[(df["Name"]=="Bob") & (df["Age"]>20)] # using and & or |

   StudentID Name  Age Gender    City Course  Marks  Attendance Passed
1        102  Bob   21   Male  Mumbai   Java     78          88    Yes

In [23]:
# Querying with .query()


df.query("Age > 20 and Name=='Ethan'")

   StudentID   Name  Age Gender       City Course  Marks  Attendance Passed
4        105  Ethan   23   Male  Hyderabad   Java     55          72     No

# Data Cleaning & Preprocessing