In [30]:
import pandas as pd

df = pd.read_csv("sample.csv")
df.shape

(16, 10)

# Handling Missing Values

In [31]:
# Check for Missing Data  

df.isnull()

,EmployeeID,Name,Age,Department,Salary,JoiningDate,Email,City,PerformanceScore,DuplicateFlag
0,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,True
2,False,False,True,False,False,True,True,False,True,True
3,False,True,False,False,True,False,False,False,False,True
4,False,False,False,True,False,False,False,False,False,True
5,False,False,False,False,False,False,False,True,False,True
6,False,False,False,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,True
9,False,False,False,False,True,False,False,False,False,True
10,False,False,False,False,False,False,False,False,False,True
11,False,False,True,False,False,False,False,False,False,True
12,False,False,False,False,False,False,False,False,True,True
13,False,False,False,False,False,False,False,False,False,True
14,False,False,False,False,False,False,False,False,False,True
15,False,False,False,False,False,False,False,False,False,True

In [32]:
df.isnull().sum() # total null values in column

EmployeeID           0
Name                 1
Age                  2
Department           1
Salary               2
JoiningDate          1
Email                1
City                 1
PerformanceScore     2
DuplicateFlag       16
dtype: int64

In [33]:
# Drop Missing Data

df.dropna()
df.dropna(axis=1)
df.shape

(16, 10)

In [34]:
# Fill Missing Data

df.fillna(0) # fill the nans with 0

,EmployeeID,Name,Age,Department,Salary,JoiningDate,Email,City,PerformanceScore,DuplicateFlag
0,101,Alice,25.0,HR,45000.0,2021-01-10,alice@example.com,Pune,88.0,0.0
1,102,Bob,30.0,IT,60000.0,2020-06-15,bob@example.com,Mumbai,92.0,0.0
2,103,Charlie,0.0,Sales,55000.0,0,0,Delhi,0.0,0.0
3,104,0,45.0,IT,0.0,2019-08-01,david@example,Pune,75.0,0.0
4,105,Eva,29.0,0,48000.0,2022-03-20,eva@example.com,Mumbai,81.0,0.0
5,106,Frank,150.0,Finance,999999.0,2020-12-12,frank@example.com,0,99.0,0.0
6,107,Grace,31.0,HR,52000.0,2021-11-11,grace@example.com,Delhi,85.0,0.0
7,108,Henry,28.0,Sales,51000.0,invalid_date,henry@example.com,Pune,82.0,0.0
8,109,Ivy,-5.0,IT,49000.0,2023-01-01,ivy@example.com,Mumbai,77.0,0.0
9,110,Jack,40.0,HR,0.0,2022-09-09,jack@example.com,Delhi,90.0,0.0
10,111,Kate,35.0,Finance,58000.0,2020-05-05,kate@example.com,Pune,86.0,0.0
11,112,Leo,0.0,IT,61000.0,2021-04-14,leo@example.com,Mumbai,84.0,0.0
12,113,Mia,27.0,Sales,47000.0,2023-02-28,mia@example.com,Delhi,0.0,0.0
13,114,Nina,29.0,HR,46000.0,2022-07-07,nina@example.com,Pune,80.0,0.0
14,115,Oscar,30.0,IT,60000.0,2020-10-10,oscar@example.com,Mumbai,91.0,0.0
15,102,Bob,30.0,IT,60000.0,2020-06-15,bob@example.com,Mumbai,92.0,0.0

In [35]:
df["Age"].fillna(df["Age"].mean())
# df["Age"].fillna(value)

0      25.000000
1      30.000000
2      37.428571
3      45.000000
4      29.000000
5     150.000000
6      31.000000
7      28.000000
8      -5.000000
9      40.000000
10     35.000000
11     37.428571
12     27.000000
13     29.000000
14     30.000000
15     30.000000
Name: Age, dtype: float64

In [36]:
df.ffill() # give forward value to nan means above box

,EmployeeID,Name,Age,Department,Salary,JoiningDate,Email,City,PerformanceScore,DuplicateFlag
0,101,Alice,25.0,HR,45000.0,2021-01-10,alice@example.com,Pune,88.0,NaN
1,102,Bob,30.0,IT,60000.0,2020-06-15,bob@example.com,Mumbai,92.0,NaN
2,103,Charlie,30.0,Sales,55000.0,2020-06-15,bob@example.com,Delhi,92.0,NaN
3,104,Charlie,45.0,IT,55000.0,2019-08-01,david@example,Pune,75.0,NaN
4,105,Eva,29.0,IT,48000.0,2022-03-20,eva@example.com,Mumbai,81.0,NaN
5,106,Frank,150.0,Finance,999999.0,2020-12-12,frank@example.com,Mumbai,99.0,NaN
6,107,Grace,31.0,HR,52000.0,2021-11-11,grace@example.com,Delhi,85.0,NaN
7,108,Henry,28.0,Sales,51000.0,invalid_date,henry@example.com,Pune,82.0,NaN
8,109,Ivy,-5.0,IT,49000.0,2023-01-01,ivy@example.com,Mumbai,77.0,NaN
9,110,Jack,40.0,HR,49000.0,2022-09-09,jack@example.com,Delhi,90.0,NaN
10,111,Kate,35.0,Finance,58000.0,2020-05-05,kate@example.com,Pune,86.0,NaN
11,112,Leo,35.0,IT,61000.0,2021-04-14,leo@example.com,Mumbai,84.0,NaN
12,113,Mia,27.0,Sales,47000.0,2023-02-28,mia@example.com,Delhi,84.0,NaN
13,114,Nina,29.0,HR,46000.0,2022-07-07,nina@example.com,Pune,80.0,NaN
14,115,Oscar,30.0,IT,60000.0,2020-10-10,oscar@example.com,Mumbai,91.0,NaN
15,102,Bob,30.0,IT,60000.0,2020-06-15,bob@example.com,Mumbai,92.0,NaN

In [37]:
df.bfill()  # give backwardward value to nan means below box

,EmployeeID,Name,Age,Department,Salary,JoiningDate,Email,City,PerformanceScore,DuplicateFlag
0,101,Alice,25.0,HR,45000.0,2021-01-10,alice@example.com,Pune,88.0,NaN
1,102,Bob,30.0,IT,60000.0,2020-06-15,bob@example.com,Mumbai,92.0,NaN
2,103,Charlie,45.0,Sales,55000.0,2019-08-01,david@example,Delhi,75.0,NaN
3,104,Eva,45.0,IT,48000.0,2019-08-01,david@example,Pune,75.0,NaN
4,105,Eva,29.0,Finance,48000.0,2022-03-20,eva@example.com,Mumbai,81.0,NaN
5,106,Frank,150.0,Finance,999999.0,2020-12-12,frank@example.com,Delhi,99.0,NaN
6,107,Grace,31.0,HR,52000.0,2021-11-11,grace@example.com,Delhi,85.0,NaN
7,108,Henry,28.0,Sales,51000.0,invalid_date,henry@example.com,Pune,82.0,NaN
8,109,Ivy,-5.0,IT,49000.0,2023-01-01,ivy@example.com,Mumbai,77.0,NaN
9,110,Jack,40.0,HR,58000.0,2022-09-09,jack@example.com,Delhi,90.0,NaN
10,111,Kate,35.0,Finance,58000.0,2020-05-05,kate@example.com,Pune,86.0,NaN
11,112,Leo,27.0,IT,61000.0,2021-04-14,leo@example.com,Mumbai,84.0,NaN
12,113,Mia,27.0,Sales,47000.0,2023-02-28,mia@example.com,Delhi,80.0,NaN
13,114,Nina,29.0,HR,46000.0,2022-07-07,nina@example.com,Pune,80.0,NaN
14,115,Oscar,30.0,IT,60000.0,2020-10-10,oscar@example.com,Mumbai,91.0,NaN
15,102,Bob,30.0,IT,60000.0,2020-06-15,bob@example.com,Mumbai,92.0,NaN

# Detecting & Removing Duplicates

In [38]:
df.duplicated() # gives that is there duplicate value or not

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
dtype: bool

In [39]:
df.drop_duplicates()

,EmployeeID,Name,Age,Department,Salary,JoiningDate,Email,City,PerformanceScore,DuplicateFlag
0,101,Alice,25.0,HR,45000.0,2021-01-10,alice@example.com,Pune,88.0,NaN
1,102,Bob,30.0,IT,60000.0,2020-06-15,bob@example.com,Mumbai,92.0,NaN
2,103,Charlie,NaN,Sales,55000.0,NaN,NaN,Delhi,NaN,NaN
3,104,NaN,45.0,IT,NaN,2019-08-01,david@example,Pune,75.0,NaN
4,105,Eva,29.0,NaN,48000.0,2022-03-20,eva@example.com,Mumbai,81.0,NaN
5,106,Frank,150.0,Finance,999999.0,2020-12-12,frank@example.com,NaN,99.0,NaN
6,107,Grace,31.0,HR,52000.0,2021-11-11,grace@example.com,Delhi,85.0,NaN
7,108,Henry,28.0,Sales,51000.0,invalid_date,henry@example.com,Pune,82.0,NaN
8,109,Ivy,-5.0,IT,49000.0,2023-01-01,ivy@example.com,Mumbai,77.0,NaN
9,110,Jack,40.0,HR,NaN,2022-09-09,jack@example.com,Delhi,90.0,NaN
10,111,Kate,35.0,Finance,58000.0,2020-05-05,kate@example.com,Pune,86.0,NaN
11,112,Leo,NaN,IT,61000.0,2021-04-14,leo@example.com,Mumbai,84.0,NaN
12,113,Mia,27.0,Sales,47000.0,2023-02-28,mia@example.com,Delhi,NaN,NaN
13,114,Nina,29.0,HR,46000.0,2022-07-07,nina@example.com,Pune,80.0,NaN
14,115,Oscar,30.0,IT,60000.0,2020-10-10,oscar@example.com,Mumbai,91.0,NaN

In [40]:
df.duplicated(subset=["Name", "Age"])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
dtype: bool